USE [master]
GO
/****** Object:  Database [E-TEACHER_DB]    Script Date: 19/3/2024 14:04:40 ******/
CREATE DATABASE [E-TEACHER_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'profe_app', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\profe_app.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'profe_app_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\profe_app_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [E-TEACHER_DB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [E-TEACHER_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [E-TEACHER_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [E-TEACHER_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [E-TEACHER_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [E-TEACHER_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [E-TEACHER_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [E-TEACHER_DB] SET  MULTI_USER 
GO
ALTER DATABASE [E-TEACHER_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [E-TEACHER_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [E-TEACHER_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [E-TEACHER_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [E-TEACHER_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [E-TEACHER_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [E-TEACHER_DB] SET QUERY_STORE = ON
GO
ALTER DATABASE [E-TEACHER_DB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [E-TEACHER_DB]
GO
/****** Object:  Schema [profe_app]    Script Date: 19/3/2024 14:04:40 ******/
CREATE SCHEMA [profe_app]
GO
/****** Object:  Table [dbo].[alumnos]    Script Date: 19/3/2024 14:04:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[alumnos](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[apellido] [varchar](50) NULL,
	[nombre] [varchar](50) NULL,
	[activo] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[cursos]    Script Date: 19/3/2024 14:04:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[cursos](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[curso_materia] [varchar](50) NOT NULL,
	[dia_horario] [varchar](50) NOT NULL,
	[institucion] [varchar](50) NOT NULL,
	[nivel] [varchar](50) NOT NULL,
	[activo] [bit] NULL,
	[anio] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[cursos_alumnos]    Script Date: 19/3/2024 14:04:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[cursos_alumnos](
	[curso] [int] NULL,
	[alumno] [int] NULL,
	[nota] [float] NULL,
	[finalizado] [bit] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[nivel]    Script Date: 19/3/2024 14:04:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[nivel](
	[id] [int] NULL,
	[nivel] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[notas]    Script Date: 19/3/2024 14:04:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[notas](
	[id_alumno] [int] NOT NULL,
	[id_curso] [int] NOT NULL,
	[nota_alumno] [float] NOT NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [E-TEACHER_DB] SET  READ_WRITE 
GO
